services:
  client:
    build: ./client
    ports:
      - "4200:80"
    networks:
      - app-network

  serveur:
    build: ./serveur
    ports:
      - "8080:8080"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge