services:
  client:
    build: ./client
    ports:
      - "4201:80"
    networks:
      - app-network
    volumes:
      - ./client:/app

  serveur:
    build: ./serveur
    ports:
      - "8080:8080"
    networks:
      - app-network
    volumes:
      - ./serveur:/app
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/tpfullstack
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: tpfullstack
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    networks:
      - app-network
    volumes:
      - postgres_data:/var/lib/postgresql/data

networks:
  app-network:
    driver: bridge

volumes:
  mysql_data: {}
  postgres_data: {}
