name: CI client

on:
  push:
    branches: [master, develop, release]
  pull_request:
    branches: [master, develop, release]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: |
          cd Client
          npm install

      - name: Run tests
        run: |
          cd Client

      - name: Build Angular app
        run: |
          cd Client
          npm run build --prod
